### PR TITLE
fix(jsonrpc): support blockHash param and genesis block process for eth_getBlockReceipts

### LINKED ISSUE #5910: Implement eth_getBlockReceipts method
# Background
I noticed that method `eth_getBlockReceipts` is not implemented in the java-tron node, making it incompatible with tooling that expects proper specification implementation (for example, TheGraph)

# Rationale
`eth_getBlockReceipts` is a part of the Ethereum [JSON-RPC Specification ](https://ethereum.github.io/execution-apis/api-documentation/) since [August 2023](https://github.com/ethereum/execution-apis/pull/438), and is based on the method with the same name present in various node implementations (geth, erigon) as well as in QuickNode and Alchemy.

# Specification
See `eth_getBlockReceipts` in https://ethereum.github.io/execution-apis/api-documentation/

# Implementation
Not yet implemented

### PR DESCRIPTION
**Pull request by 0xbigapple**
**What does this PR do?**

eth_getBlockReceipts api :  1. return null for genesis block 2. support blockHash param

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Review by kuny0707 — APPROVED** [review]

**Review by halibobo1205 — APPROVED** [review]

File: framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java [hunk 1]
```diff
@@ -849,7 +849,9 @@ private TransactionContext findTransactionContext(TransactionInfoList infoList,
   public List<TransactionReceipt> getBlockReceipts(String blockNumOrTag)
       throws JsonRpcInvalidParamsException, JsonRpcInternalException {
     Block block = wallet.getByJsonBlockId(blockNumOrTag);
-    if (block == null) {
+
```
Comment (waynercheung) [inline framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java:860]: line 862, "//energy price at the block timestamp" --> "// energy price at the block timestamp"

File: framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java [hunk 2]
```diff
@@ -849,7 +849,9 @@ private TransactionContext findTransactionContext(TransactionInfoList infoList,
...
+    // block receipts not available: block is genesis, not produced yet, or pruned in light node
+    if (block == null || block.getBlockHeader().getRawData().getNumber() == 0) {
```
Comment (waynercheung) [inline framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java:862]: Does the eth_getBlockReceipts support blockHash as a parameter?

File: framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java (hunk 1 above)
Comment (waynercheung) [reply framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java:852]: besides, in the function findTransactionContext, please check the logic of cumulativeGas and cumulativeLogCount, they all need to add the own value of the transaction itself.

Comment (0xbigapple) [reply framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java:860]: ok

File: framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java (hunk 2 above)
Comment (0xbigapple) [reply framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java:862]: eth_getBlockReceipts  on ethernum support blockHash, I have a new commit to support it.https://github.com/tronprotocol/java-tron/pull/6433/commits/8570eea285dd6c078612afe8042fae54e36a974f

**Review by lvs0075 — APPROVED** [review]
